/**
 * Database Types
 *
 * This file will be generated by Supabase CLI after setting up the project.
 * Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.ts
 *
 * For now, using a placeholder type.
 */

export type Database = {
  public: {
    Tables: {
      [key: string]: {
        Row: Record<string, unknown>;
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
      };
    };
  };
};
